### ISSUE TITLE
Use 5px border radius on a selected row

### ISSUE THREAD

**Issue by atpollmann** [Karmasian/veti-medical-react-desktop#36]
![Screen Shot 2019-07-14 at 9 31 59 PM](https://user-images.githubusercontent.com/10424410/61192010-e6378880-a67e-11e9-8444-ca80c6809324.png)

**Comment by marianobria** [comment]
Esto aplica tambien al comentario q deje en el bug #34 
Esta tabla (mui-datatables) no es muy predispuesta a customizaciones de este tipo, pero se puede anadir a la wishlist de improvements de esa tabla.

**Comment by atpollmann** [comment]
Added to wishlist bucket that probably will never be
