### ISSUE TITLE
Stilize table paginator according to design

### ISSUE THREAD

**Issue by atpollmann** [Karmasian/veti-medical-react-desktop#38]
![Screen Shot 2019-07-14 at 9 42 27 PM](https://user-images.githubusercontent.com/10424410/61192155-4d097180-a680-11e9-9417-38828f987fb6.png)

**Comment by marianobria** [comment]
Este cambio ocasionaria crear un custom footer completo con su estilo y funcionalidad, ya que el paginator  es parte de la libreria de la tabla y no es flexible a customizarlo en su estilo sin modificar el estilo de la libreria en si.

**Comment by atpollmann** [comment]
Se mueve a whish list
