### ISSUE TITLE
Adjust colors according to design

### ISSUE THREAD

**Issue by atpollmann** [Karmasian/veti-medical-react-desktop#40]
- Table headers (```th```) must be ```#a6aab5```
- p, h's, etc. must be ```#1a1a34```
- Use bolder font in the mascot name
- Checkbox border color
- Hover on a contextual menu item must be ```pale-gray```(```#f6f8fb```)

**Comment by marianobria** [comment]
En este caso el checkbox border es parte de un span que contiene un svg q es el boton clickeable, se deberia cambiar el estilo completo de como esta armado el boton del checkbox para lograr un border a nivel del svg icon.
